import type { ClassificationRule } from '../types';

export const DEFAULT_RULES: ClassificationRule[] = [
  // ── 固定費 - 住居 ──
  { pattern: '家賃', category: '住居費', expenseType: 'fixed' },
  { pattern: 'マンション', category: '住居費', expenseType: 'fixed' },
  { pattern: '管理費', category: '住居費', expenseType: 'fixed' },
  { pattern: '不動産', category: '住居費', expenseType: 'fixed' },
  { pattern: '賃貸', category: '住居費', expenseType: 'fixed' },

  // ── 固定費 - 通信 ──
  { pattern: 'NTT', category: '通信費', expenseType: 'fixed' },
  { pattern: 'KDDI', category: '通信費', expenseType: 'fixed' },
  { pattern: 'AU', category: '通信費', expenseType: 'fixed' },
  { pattern: 'ソフトバンク', category: '通信費', expenseType: 'fixed' },
  { pattern: 'SOFTBANK', category: '通信費', expenseType: 'fixed' },
  { pattern: 'ドコモ', category: '通信費', expenseType: 'fixed' },
  { pattern: 'DOCOMO', category: '通信費', expenseType: 'fixed' },
  { pattern: 'NTTドコモ', category: '通信費', expenseType: 'fixed' },
  { pattern: 'ドコモ料金', category: '通信費', expenseType: 'fixed' },
  { pattern: 'D払い/通信料金', category: '通信費', expenseType: 'fixed' },
  { pattern: 'RAKUTEN MOBILE', category: '通信費', expenseType: 'fixed' },
  { pattern: '楽天モバイル', category: '通信費', expenseType: 'fixed' },
  { pattern: 'YMOBILE', category: '通信費', expenseType: 'fixed' },
  { pattern: 'ワイモバイル', category: '通信費', expenseType: 'fixed' },
  { pattern: 'UQ', category: '通信費', expenseType: 'fixed' },
  { pattern: 'NURO', category: '通信費', expenseType: 'fixed' },
  { pattern: 'OCN', category: '通信費', expenseType: 'fixed' },
  { pattern: 'BIGLOBE', category: '通信費', expenseType: 'fixed' },
  { pattern: 'LINEMO', category: '通信費', expenseType: 'fixed' },
  { pattern: 'POVO', category: '通信費', expenseType: 'fixed' },
  { pattern: 'AHAMO', category: '通信費', expenseType: 'fixed' },
  { pattern: 'マイネオ', category: '通信費', expenseType: 'fixed' },
  { pattern: 'MINEO', category: '通信費', expenseType: 'fixed' },
  { pattern: 'IIJMIO', category: '通信費', expenseType: 'fixed' },
  { pattern: '通信料', category: '通信費', expenseType: 'fixed' },
  { pattern: '電話料', category: '通信費', expenseType: 'fixed' },
  { pattern: 'スマートデバイス', category: '通信費', expenseType: 'fixed' },

  // ── 固定費 - 保険 ──
  { pattern: '保険', category: '保険料', expenseType: 'fixed' },
  { pattern: '共済', category: '保険料', expenseType: 'fixed' },
  { pattern: 'ライフネット', category: '保険料', expenseType: 'fixed' },

  // ── 固定費 - サブスクリプション ──
  { pattern: 'NETFLIX', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'ネットフリックス', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'SPOTIFY', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'AMAZON PRIME', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'APPLE.COM/BILL', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'APPLE COM BILL', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'GOOGLE STORAGE', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'GOOGLE ONE', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'GOOGLE *', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'YOUTUBE PREMIUM', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'YOUTUBE MUSIC', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'DISNEY PLUS', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'DISNEY+', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'HULU', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'DAZN', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'ABEMA', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'U-NEXT', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'CHATGPT', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'OPENAI', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'NOTION', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'ADOBE', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'MICROSOFT 365', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'DROPBOX', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'ICLOUD', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'コネクトサービス', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'バンダイチャンネル', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'CRUNCHYROLL', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'KINDLE UNLIMITED', category: 'サブスク', expenseType: 'fixed' },
  { pattern: 'AUDIBLE', category: 'サブスク', expenseType: 'fixed' },

  // ── 固定費 - 光熱費 ──
  { pattern: '電力', category: '光熱費', expenseType: 'fixed' },
  { pattern: 'ガス', category: '光熱費', expenseType: 'fixed' },
  { pattern: '水道', category: '光熱費', expenseType: 'fixed' },
  { pattern: 'エネルギー', category: '光熱費', expenseType: 'fixed' },
  { pattern: 'TEPCO', category: '光熱費', expenseType: 'fixed' },
  { pattern: '東京電力', category: '光熱費', expenseType: 'fixed' },
  { pattern: '東京ガス', category: '光熱費', expenseType: 'fixed' },
  { pattern: '大阪ガス', category: '光熱費', expenseType: 'fixed' },
  { pattern: '関西電力', category: '光熱費', expenseType: 'fixed' },
  { pattern: '中部電力', category: '光熱費', expenseType: 'fixed' },
  { pattern: 'カテエネ', category: '光熱費', expenseType: 'fixed' },
  { pattern: '中電', category: '光熱費', expenseType: 'fixed' },
  { pattern: '東北電力', category: '光熱費', expenseType: 'fixed' },
  { pattern: '九州電力', category: '光熱費', expenseType: 'fixed' },
  { pattern: 'ENEOS電気', category: '光熱費', expenseType: 'fixed' },
  { pattern: 'ENEOSでんき', category: '光熱費', expenseType: 'fixed' },
  { pattern: '楽天でんき', category: '光熱費', expenseType: 'fixed' },

  // ── 変動費 - 食費（スーパー・コンビニ） ──
  { pattern: 'スーパー', category: '食費', expenseType: 'variable' },
  { pattern: 'イオン', category: '食費', expenseType: 'variable' },
  { pattern: 'マックスバリュ', category: '食費', expenseType: 'variable' },
  { pattern: 'ライフ', category: '食費', expenseType: 'variable' },
  { pattern: 'セブンイレブン', category: '食費', expenseType: 'variable' },
  { pattern: 'セブン-イレブン', category: '食費', expenseType: 'variable' },
  { pattern: 'セブン‐イレブン', category: '食費', expenseType: 'variable' },
  { pattern: 'セブンーイレブン', category: '食費', expenseType: 'variable' },
  { pattern: 'ファミリーマート', category: '食費', expenseType: 'variable' },
  { pattern: 'ファミマ', category: '食費', expenseType: 'variable' },
  { pattern: 'ローソン', category: '食費', expenseType: 'variable' },
  { pattern: 'LAWSON', category: '食費', expenseType: 'variable' },
  { pattern: 'ミニストップ', category: '食費', expenseType: 'variable' },
  { pattern: 'デイリーヤマザキ', category: '食費', expenseType: 'variable' },
  { pattern: 'セイコーマート', category: '食費', expenseType: 'variable' },
  { pattern: 'ポプラ', category: '食費', expenseType: 'variable' },
  { pattern: 'NEWDAYS', category: '食費', expenseType: 'variable' },
  { pattern: 'ニューデイズ', category: '食費', expenseType: 'variable' },
  { pattern: 'コンビニ', category: '食費', expenseType: 'variable' },
  { pattern: 'まいばすけっと', category: '食費', expenseType: 'variable' },
  { pattern: 'サミット', category: '食費', expenseType: 'variable' },
  { pattern: 'ヨークマート', category: '食費', expenseType: 'variable' },
  { pattern: 'いなげや', category: '食費', expenseType: 'variable' },
  { pattern: 'オーケー', category: '食費', expenseType: 'variable' },
  { pattern: 'OK ストア', category: '食費', expenseType: 'variable' },
  { pattern: 'コストコ', category: '食費', expenseType: 'variable' },
  { pattern: 'COSTCO', category: '食費', expenseType: 'variable' },
  { pattern: '業務スーパー', category: '食費', expenseType: 'variable' },
  { pattern: '西友', category: '食費', expenseType: 'variable' },
  { pattern: 'SEIYU', category: '食費', expenseType: 'variable' },
  { pattern: 'ダイエー', category: '食費', expenseType: 'variable' },
  { pattern: 'ヤオコー', category: '食費', expenseType: 'variable' },
  { pattern: 'ベルク', category: '食費', expenseType: 'variable' },
  { pattern: 'カスミ', category: '食費', expenseType: 'variable' },
  { pattern: 'マルエツ', category: '食費', expenseType: 'variable' },
  { pattern: 'ピーコック', category: '食費', expenseType: 'variable' },
  { pattern: 'オオゼキ', category: '食費', expenseType: 'variable' },
  { pattern: 'MY PROTEIN', category: '食費', expenseType: 'variable' },
  { pattern: 'MYPROTEIN', category: '食費', expenseType: 'variable' },

  // ── 変動費 - 外食 ──
  { pattern: 'レストラン', category: '外食費', expenseType: 'variable' },
  { pattern: 'マクドナルド', category: '外食費', expenseType: 'variable' },
  { pattern: 'マックデリバリ', category: '外食費', expenseType: 'variable' },
  { pattern: 'スターバックス', category: '外食費', expenseType: 'variable' },
  { pattern: 'STARBUCKS', category: '外食費', expenseType: 'variable' },
  { pattern: 'ケンタッキー', category: '外食費', expenseType: 'variable' },
  { pattern: 'すき家', category: '外食費', expenseType: 'variable' },
  { pattern: '吉野家', category: '外食費', expenseType: 'variable' },
  { pattern: '松屋', category: '外食費', expenseType: 'variable' },
  { pattern: 'カフェ', category: '外食費', expenseType: 'variable' },
  { pattern: 'CoCo壱番屋', category: '外食費', expenseType: 'variable' },
  { pattern: 'ココイチ', category: '外食費', expenseType: 'variable' },
  { pattern: 'モスバーガー', category: '外食費', expenseType: 'variable' },
  { pattern: 'バーガーキング', category: '外食費', expenseType: 'variable' },
  { pattern: 'サイゼリヤ', category: '外食費', expenseType: 'variable' },
  { pattern: 'ガスト', category: '外食費', expenseType: 'variable' },
  { pattern: 'デニーズ', category: '外食費', expenseType: 'variable' },
  { pattern: 'ジョナサン', category: '外食費', expenseType: 'variable' },
  { pattern: 'ロイヤルホスト', category: '外食費', expenseType: 'variable' },
  { pattern: '丸亀製麺', category: '外食費', expenseType: 'variable' },
  { pattern: '天下一品', category: '外食費', expenseType: 'variable' },
  { pattern: '日高屋', category: '外食費', expenseType: 'variable' },
  { pattern: 'ドトール', category: '外食費', expenseType: 'variable' },
  { pattern: 'タリーズ', category: '外食費', expenseType: 'variable' },
  { pattern: 'TULLY', category: '外食費', expenseType: 'variable' },
  { pattern: 'コメダ', category: '外食費', expenseType: 'variable' },
  { pattern: 'UBER *EATS', category: '外食費', expenseType: 'variable' },
  { pattern: 'UBER*EATS', category: '外食費', expenseType: 'variable' },
  { pattern: 'UBEREATS', category: '外食費', expenseType: 'variable' },
  { pattern: 'ウーバーイーツ', category: '外食費', expenseType: 'variable' },
  { pattern: '出前館', category: '外食費', expenseType: 'variable' },
  { pattern: 'DEMAECAN', category: '外食費', expenseType: 'variable' },
  { pattern: 'WOLT', category: '外食費', expenseType: 'variable' },
  { pattern: 'MENU', category: '外食費', expenseType: 'variable' },

  // ── 変動費 - 交通 ──
  { pattern: '交通', category: '交通費', expenseType: 'variable' },
  { pattern: 'JR', category: '交通費', expenseType: 'variable' },
  { pattern: '鉄道', category: '交通費', expenseType: 'variable' },
  { pattern: 'タクシー', category: '交通費', expenseType: 'variable' },
  { pattern: 'ETC', category: '交通費', expenseType: 'variable' },
  { pattern: 'ガソリン', category: '交通費', expenseType: 'variable' },
  { pattern: 'ENEOS', category: '交通費', expenseType: 'variable' },
  { pattern: '出光', category: '交通費', expenseType: 'variable' },
  { pattern: 'シェル', category: '交通費', expenseType: 'variable' },
  { pattern: '駐車', category: '交通費', expenseType: 'variable' },
  { pattern: 'パーキング', category: '交通費', expenseType: 'variable' },
  { pattern: 'SUICA', category: '交通費', expenseType: 'variable' },
  { pattern: 'PASMO', category: '交通費', expenseType: 'variable' },
  { pattern: 'バイチャージ', category: '交通費', expenseType: 'variable' },
  { pattern: 'ANA', category: '交通費', expenseType: 'variable' },
  { pattern: 'JAL', category: '交通費', expenseType: 'variable' },
  { pattern: 'PEACH', category: '交通費', expenseType: 'variable' },
  { pattern: 'JETSTAR', category: '交通費', expenseType: 'variable' },
  { pattern: '新幹線', category: '交通費', expenseType: 'variable' },
  { pattern: 'タイムズ', category: '交通費', expenseType: 'variable' },

  // ── 変動費 - 日用品 ──
  { pattern: 'ドラッグ', category: '日用品', expenseType: 'variable' },
  { pattern: '薬局', category: '日用品', expenseType: 'variable' },
  { pattern: 'マツモトキヨシ', category: '日用品', expenseType: 'variable' },
  { pattern: 'マツキヨ', category: '日用品', expenseType: 'variable' },
  { pattern: 'ウエルシア', category: '日用品', expenseType: 'variable' },
  { pattern: 'ツルハ', category: '日用品', expenseType: 'variable' },
  { pattern: 'スギ薬局', category: '日用品', expenseType: 'variable' },
  { pattern: 'サンドラッグ', category: '日用品', expenseType: 'variable' },
  { pattern: 'ココカラファイン', category: '日用品', expenseType: 'variable' },
  { pattern: 'トモズ', category: '日用品', expenseType: 'variable' },
  { pattern: 'ダイソー', category: '日用品', expenseType: 'variable' },
  { pattern: 'セリア', category: '日用品', expenseType: 'variable' },
  { pattern: 'キャンドゥ', category: '日用品', expenseType: 'variable' },
  { pattern: '100円', category: '日用品', expenseType: 'variable' },

  // ── 変動費 - ショッピング ──
  { pattern: 'AMAZON', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'アマゾン', category: 'ショッピング', expenseType: 'variable' },
  { pattern: '楽天', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'YAHOO', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ユニクロ', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'UNIQLO', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'GU', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ニトリ', category: 'ショッピング', expenseType: 'variable' },
  { pattern: '無印', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'MUJI', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ZARA', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'H&M', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'しまむら', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ワークマン', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ヨドバシ', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ビックカメラ', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ヤマダ電機', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'エディオン', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'ケーズデンキ', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'PAYPAL', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'メルカリ', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'MERCARI', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'SHEIN', category: 'ショッピング', expenseType: 'variable' },
  { pattern: 'TEMU', category: 'ショッピング', expenseType: 'variable' },

  // ── 変動費 - 医療 ──
  { pattern: '病院', category: '医療費', expenseType: 'variable' },
  { pattern: 'クリニック', category: '医療費', expenseType: 'variable' },
  { pattern: '医院', category: '医療費', expenseType: 'variable' },
  { pattern: '歯科', category: '医療費', expenseType: 'variable' },
  { pattern: '調剤', category: '医療費', expenseType: 'variable' },
  { pattern: '薬局', category: '医療費', expenseType: 'variable' },
  { pattern: '整骨', category: '医療費', expenseType: 'variable' },
  { pattern: '整体', category: '医療費', expenseType: 'variable' },
  { pattern: '眼科', category: '医療費', expenseType: 'variable' },
  { pattern: '皮膚科', category: '医療費', expenseType: 'variable' },
  { pattern: '内科', category: '医療費', expenseType: 'variable' },

  // ── 変動費 - 娯楽 ──
  { pattern: '映画', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'TOHO', category: '娯楽費', expenseType: 'variable' },
  { pattern: '書店', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'BOOK', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'ゲーム', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'STEAM', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'PLAYSTATION', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'NINTENDO', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'カラオケ', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'ボウリング', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'ジム', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'フィットネス', category: '娯楽費', expenseType: 'variable' },
  { pattern: 'PELOTON', category: '娯楽費', expenseType: 'variable' },

  // ── 変動費 - 教育 ──
  { pattern: '学校', category: '教育費', expenseType: 'variable' },
  { pattern: '塾', category: '教育費', expenseType: 'variable' },
  { pattern: '予備校', category: '教育費', expenseType: 'variable' },
  { pattern: 'UDEMY', category: '教育費', expenseType: 'variable' },
  { pattern: 'COURSERA', category: '教育費', expenseType: 'variable' },

  // ── 投資 ──
  { pattern: '証券', category: '投資', expenseType: 'fixed' },
  { pattern: '投資', category: '投資', expenseType: 'fixed' },
  { pattern: 'SBI', category: '投資', expenseType: 'fixed' },
  { pattern: '積立', category: '投資', expenseType: 'fixed' },
  { pattern: 'NISA', category: '投資', expenseType: 'fixed' },
  { pattern: 'IDECO', category: '投資', expenseType: 'fixed' },
  { pattern: 'ＩＤＥ', category: '投資', expenseType: 'fixed' },
];

export const CATEGORIES = [
  '住居費',
  '通信費',
  '保険料',
  'サブスク',
  '光熱費',
  '食費',
  '外食費',
  '交通費',
  '日用品',
  'ショッピング',
  '医療費',
  '娯楽費',
  '教育費',
  '投資',
  'その他',
];
